// Automatically generated by astro-icon
// 001f41afe570549b27613a610a60077c3c328e6e7910f3555cd572939299ecf1

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-right"
		| "box"
		| "check"
		| "database"
		| "display"
		| "help"
		| "minus";
}